#!/bin/zsh

# Stores arguments passed by the user
function storeargs {
	argnum=1;
	for i in $@
	do
		arg[((argnum))]=$i;
		((argnum++));
	done
	
	while [ $argnum -le 9 ]
	do
		arg[((argnum))]=$argnum;
		((argnum++));
	done
}

storeargs $@

dir=~/AUR_pkgs/dwm/dwm # location of configuration file
N=19 # line number of where the tags are in your path

# this will change config.h's tags in order of user input
sed -i "${N}s/{.*/{ \"${arg[1]}\", \"${arg[2]}\", \"${arg[3]}\", \"${arg[4]}\", \"${arg[5]}\", \"${arg[6]}\", \"${arg[7]}\", \"${arg[8]}\", \"${arg[9]}\" };/" $dir/config.h

cd ${dir}
makepkg -efi
